In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("/content/Iris.csv")

In [16]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [17]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [18]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [19]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [21]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [25]:
x = df.drop(columns =(['Id',"Species"]))

In [26]:
x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [27]:
y = df['Species']

In [28]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=56)

In [31]:
x_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
112            6.8           3.0            5.5           2.1
101            5.8           2.7            5.1           1.9
72             6.3           2.5            4.9           1.5
40             5.0           3.5            1.3           0.3
38             4.4           3.0            1.3           0.2
..             ...           ...            ...           ...
87             6.3           2.3            4.4           1.3
142            5.8           2.7            5.1           1.9
122            7.7           2.8            6.7           2.0
143            6.8           3.2            5.9           2.3
85             6.0           3.4            4.5           1.6

[120 rows x 4 columns]

In [32]:
x_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137            6.4           3.1            5.5           1.8
98             5.1           2.5            3.0           1.1
77             6.7           3.0            5.0           1.7
141            6.9           3.1            5.1           2.3
120            6.9           3.2            5.7           2.3
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
35             5.0           3.2            1.2           0.2
12             4.8           3.0            1.4           0.1
127            6.1           3.0            4.9           1.8
71             6.1           2.8            4.0           1.3
4              5.0           3.6            1.4           0.2
0              5.1           3.5            1.4           0.2
18             5.7           3.8            1.7           0.3
83             6.0           2.7            5.1           1.6
6              4.6           3.4            1.4           0.3
7              5.0           3.4            1.5           0.2
9              4.9           3.1            1.5           0.1
103            6.3           2.9            5.6           1.8
81             5.5           2.4            3.7           1.0
42             4.4           3.2            1.3           0.2
108            6.7           2.5            5.8           1.8
57             4.9           2.4            3.3           1.0
68             6.2           2.2            4.5           1.5
30             4.8           3.1            1.6           0.2
104            6.5           3.0            5.8           2.2
105            7.6           3.0            6.6           2.1
63             6.1           2.9            4.7           1.4
73             6.1           2.8            4.7           1.2
53             5.5           2.3            4.0           1.3

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
knn = KNeighborsClassifier()

In [38]:
model = knn.fit(x_train,y_train)

In [39]:
y_pred = model.predict(x_test)

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [41]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [44]:
cr = classification_report(y_test,y_pred)
print(cr)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

In [45]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[10,  0,  0],
       [ 0,  9,  1],
       [ 0,  0, 10]])

In [46]:
import joblib

In [47]:
model = joblib.dump(model,"iris_model.pkl")

In [50]:
pip install streamlit

Collecting streamlit
  Downloading streamlit-1.64.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.52.4)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.25.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.19)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.64.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 25.1 MB/s eta 0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 40.9 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.3 streamlit-1.64.0

In [55]:
#deployment
import streamlit as st
import numpy as np

In [52]:
#load model
model = joblib.load("iris_model.pkl")

In [53]:
#page title
st.title("machine learning on iris dataset")

2026-09-17 05:42:15.992 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:42:16.291
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.13/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-09-17 05:42:16.292 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:42:16.293 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [54]:
#input labels
sepal_length = st.number_input("sepal_length")
sepal_width = st.number_input("sepal_width")
petal_length = st.number_input("petal_length")
petal_width = st.number_input("petal_width")

2026-09-17 05:47:15.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.204 Session state does not function when running a script without `streamlit run`
2026-09-17 05:47:15.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.220 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.226 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.227 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.231 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:47:15.235 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [56]:
#prediction
if st.button("predict"):
  input = np.array([[sepal_length,
                     sepal_width,
                     petal_length,
                     petal_width]]).astype(np.float64)
  prediction = model.predict(input)
  st.success(prediction)

2026-09-17 05:49:12.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:49:12.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:49:12.878 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:49:12.879 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-17 05:49:12.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.